name: SaneEconomyOnlineTime
main: org.appledash.saneeconomy.onlinetime.SaneEconomyOnlineTime
description: Pays players for being online!
author: AppleDash TigerClips1 jascotty2
version: ${project.version}
depend: [SaneEconomy]