name: SaneEconomyMobKills
description: A plugin to give players experience when they kill mobs.
version: ${project.version}
author: AppleDash TigerClips1 jascotty2
main: org.appledash.saneeconomymobkills.SaneEconomyMobKills
depend: [SaneEconomy]
